# -*- coding: utf-8 -*-
"""textclassification_textblob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vbRf_wz_fRUStuwzJM3RQ0N04y5jwZA
"""

#Text Classification using TextBlob
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
documents = [
    "SpaceX launches new rocket to the International Space Station.",
    "Archaeologists uncover a 2,000-year-old Roman villa in Italy.",
    "Manchester United wins a thrilling match with a late goal.",
    "NASA confirms the discovery of a new exoplanet with liquid water.",
    "A new exhibit on ancient Egyptian art opens at the museum.",
    "Real Madrid defeats Barcelona in the final of the tournament."
]
categories = ["Science", "History", "Sports", "Science", "History", "Sports"]
trainData=[]
for doc,cat in zip(documents,categories):
  tuple=doc,cat
  trainData.append(tuple)
print("Train Data:\n",trainData)

from textblob.classifiers import NaiveBayesClassifier
cl=NaiveBayesClassifier(trainData)
test_documents = [
    "Scientists find a new species of deep-sea fish.",
    "Lionel Messi signs a new contract with Paris Saint-Germain."
]
print("\nPredictions using Naive Bayes Classifier:")
for doc in test_documents:
  print(f"Document:{doc} is classified as Category:{cl.classify(doc)}")

